# ----------------------------------------------------------------------------
# Copyright 2021 The Netty Project
#
# The Netty Project licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
# ----------------------------------------------------------------------------
name: Deploy project

on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all

env:
  MAVEN_OPTS: -Xmx6g -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryhandler.count=5 -Dmaven.wagon.httpconnectionManager.ttlSeconds=240

# Cancel running jobs when a new push happens to the same branch as otherwise it will
# tie up too many resources without providing much value.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stage-snapshot-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - setup: linux-x86_64-java11
            docker-compose-build: "-f docker/docker-compose.yaml -f docker/docker-compose.centos-7.111.yaml build"
            docker-compose-run: "-f docker/docker-compose.yaml -f docker/docker-compose.centos-7.111.yaml run stage-snapshot"
            artifact-paths: |
              ~/local-staging/io/netty/netty-transport-native-epoll/*/*.jar
              !~/local-staging/io/netty/netty-transport-native-epoll/*/*-javadoc.jar
              !~/local-staging/io/netty/netty-transport-native-epoll/*/*-sources.jar
          - setup: linux-aarch64
            docker-compose-build: "-f docker/docker-compose.centos-7.cross.yaml build"
            docker-compose-run: "-f docker/docker-compose.centos-7.cross.yaml run cross-compile-aarch64-stage-snapshot"
            artifact-paths: |
              ~/local-staging/io/netty/netty-transport-native-epoll/*/*-linux-aarch_64.jar
          - setup: linux-riscv64
            docker-compose-build: "-f docker/docker-compose.ubuntu-*.cross.yaml build"
            docker-compose-run: "-f docker/docker-compose.ubuntu-*.cross.yaml run cross-compile-riscv64-stage-snapshot"
            artifact-paths: |
              ~/local-staging/io/netty/netty-transport-native-epoll/*/*-linux-riscv64.jar

    name: stage-snapshot-${{ matrix.setup }}
    steps:
      - uses: actions/checkout@v4

      # Cache .m2/repository
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: cache-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            cache-maven-${{ hashFiles('**/pom.xml') }}
            cache-maven-

      - name: Create local staging directory
        run: mkdir -p ~/local-staging

      - name: Build docker image
        run: docker compose ${{ matrix.docker-compose-build }}

      - name: Stage snapshots to local staging directory
        run: docker compose ${{ matrix.docker-compose-run }}

      - name: Upload local staging directory
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.setup }}-local-staging
          path: ${{ matrix.artifact-paths }}
          if-no-files-found: error
          include-hidden-files: true

